### ISSUE TITLE
Gulp dependency

### ISSUE THREAD

**Issue by jdillick** [camdagr8/butter-cli#1]
@camdagr8 gulp should probably be a dependency.

> Error: spawn gulp ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
    at onErrorNT (internal/child_process.js:366:16)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)

**Comment by jdillick** [comment]
Fair to say, no one cares about this. :)
